=== Sergei1291/Parser/src/test/resources/tariffs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/tariffs"
        xmlns:tns="http://www.example.com/tariffs"
        elementFormDefault="qualified">

    <element name="tariffs">
        <complexType>
            <sequence>
                <element ref="tns:abstract-tariff"
                         minOccurs="2"
                         maxOccurs="6"/>
            </sequence>
        </complexType>
    </element>

    <element name="abstract-tariff" type="tns:abstract-tariff" abstract="true"/>
    <element name="tariff" type="tns:tariff" substitutionGroup="tns:abstract-tariff"/>
    <element name="payroll-tariff" type="tns:payroll-tariff" substitutionGroup="tns:abstract-tariff"/>

    <complexType name="abstract-tariff">
        <sequence>
            <element name="price" type="tns:price"/>
        </sequence>
        <attribute name="name" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="[A-Z]([a-zA-Z0-9\-]){5,29}"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="price">
        <sequence>
            <element name="call">
                <simpleType>
                    <restriction base="positiveInteger">
                        <maxInclusive value="50"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="traffic">
                <simpleType>
                    <restriction base="positiveInteger">
                        <maxInclusive value="10"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="sms">
                <simpleType>
                    <restriction base="positiveInteger">
                        <maxInclusive value="10"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <complexType name="tariff">
        <complexContent>
            <extension base="tns:abstract-tariff">
                <sequence>
                    <element name="favorite-number">
                        <simpleType>
                            <restriction base="string">
                                <pattern value="[0-9]{9}"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="payroll-tariff">
        <complexContent>
            <extension base="tns:abstract-tariff">
                <sequence>
                    <element name="payroll">
                        <simpleType>
                            <restriction base="positiveInteger">
                                <minInclusive value="100"/>
                                <maxInclusive value="1000"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
                <attribute name="included-traffic" use="optional" default="one">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="one"/>
                            <enumeration value="two"/>
                            <enumeration value="four"/>
                            <enumeration value="eight"/>
                            <enumeration value="sixteen"/>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>

</schema>

=== Sergei1291/Parser/src/test/resources/tariffsInvalid.xml
<?xml version="1.0" encoding="utf-8" ?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/tariffs"
         xsi:schemaLocation="http://www.example.com/tariffs tariffs.xsd">

    <tariff name="First-tariff-1">
        <price>
            <call>10</call>
            <traffic>1</traffic>
            <sms>1</sms>
        </price>
        <favo rite-number>112223344</favorite-number>
    </tariff>

    <tariff name="Tariff-second">
        <price>
            <call>20</call>
            <traffic>2</traffic>
            <sms>2</sms>
        </price>
        <favorite-number>556667788</favorite-number>
    </tariff>

    <payroll-tariff name="SimplePayroll" included-traffic="one">
        <price>
            <call>3</call>
            <traffic>3</traffic>
            <sms>3</sms>
        </price>
        <payroll>300</payroll>
    </payroll-tariff>

    <payroll-tariff name="Internet-16" included-traffic="sixteen">
        <price>
            <call>4</call>
            <traffic>4</traffic>
            <sms>4</sms>
        </price>
        <payroll>400</payroll>
    </payroll-tariff>

</tariffs>
